"""Curated catalog of additional AI agents for database enrichment.

Each entry is a dict consumed by `ingest_agents.py`. Fields mirror the Agent
model: name, slug, description, short_description, website_url, logo_url,
category (slug), pricing_model, tags (slug list), featured.

Logo URLs use Google's favicon service keyed by the product's domain, which is
hotlink-friendly and far more stable than scraping each vendor's marketing site.
"""

CATALOG = [
    {
        "name": "DeepSeek",
        "slug": "deepseek",
        "description": "DeepSeek is a capable open-weights AI assistant known for strong reasoning and coding performance at low cost.",
        "short_description": "Open-weights AI assistant with strong reasoning",
        "website_url": "https://deepseek.com",
        "logo_url": "https://www.google.com/s2/favicons?domain=deepseek.com&sz=128",
        "category": "productivity",
        "pricing_model": "freemium",
        "featured": False,
        "tags": ["conversational-ai"],
    },
    {
        "name": "Grok",
        "slug": "grok",
        "description": "Grok is xAI's conversational assistant known for real-time information access and a witty, direct personality.",
        "short_description": "xAI's real-time conversational assistant",
        "website_url": "https://grok.com",
        "logo_url": "https://www.google.com/s2/favicons?domain=grok.com&sz=128",
        "category": "productivity",
        "pricing_model": "freemium",
        "featured": False,
        "tags": ["conversational-ai"],
    },
    {
        "name": "Mistral Le Chat",
        "slug": "mistral-le-chat",
        "description": "Le Chat is Mistral AI's assistant and collaboration platform for fast, high-quality chat and document analysis.",
        "short_description": "Mistral AI's fast assistant and collaboration platform",
        "website_url": "https://chat.mistral.ai",
        "logo_url": "https://www.google.com/s2/favicons?domain=mistral.ai&sz=128",
        "category": "productivity",
        "pricing_model": "freemium",
        "featured": False,
        "tags": ["conversational-ai"],
    },
    {
        "name": "Claude Code",
        "slug": "claude-code",
        "description": "Claude Code is Anthropic's agentic coding tool that runs in the terminal to plan, build, and refactor code.",
        "short_description": "Anthropic's agentic coding tool for the terminal",
        "website_url": "https://claude.com/claude-code",
        "logo_url": "https://www.google.com/s2/favicons?domain=claude.com&sz=128",
        "category": "development",
        "pricing_model": "paid",
        "featured": False,
        "tags": ["code-generation"],
    },
    {
        "name": "Windsurf",
        "slug": "windsurf",
        "description": "Windsurf is an agentic AI code editor built on VS Code with deep codebase awareness and Cascade flows.",
        "short_description": "Agentic AI code editor",
        "website_url": "https://windsurf.com",
        "logo_url": "https://www.google.com/s2/favicons?domain=windsurf.com&sz=128",
        "category": "development",
        "pricing_model": "freemium",
        "featured": False,
        "tags": ["code-generation"],
    },
    {
        "name": "v0",
        "slug": "v0",
        "description": "v0 by Vercel generates React and Tailwind UI from natural language prompts, accelerating frontend development.",
        "short_description": "Vercel's AI UI generator",
        "website_url": "https://v0.dev",
        "logo_url": "https://www.google.com/s2/favicons?domain=v0.dev&sz=128",
        "category": "development",
        "pricing_model": "freemium",
        "featured": False,
        "tags": ["code-generation"],
    },
    {
        "name": "Bolt.new",
        "slug": "bolt-new",
        "description": "Bolt.new by StackBlitz builds and runs full-stack web apps in the browser from natural language prompts.",
        "short_description": "Full-stack app development in the browser",
        "website_url": "https://bolt.new",
        "logo_url": "https://www.google.com/s2/favicons?domain=bolt.new&sz=128",
        "category": "development",
        "pricing_model": "freemium",
        "featured": False,
        "tags": ["code-generation"],
    },
    {
        "name": "Lovable",
        "slug": "lovable",
        "description": "Lovable turns natural language into full-stack applications with an AI product builder and instant deploys.",
        "short_description": "AI product builder for full-stack apps",
        "website_url": "https://lovable.dev",
        "logo_url": "https://www.google.com/s2/favicons?domain=lovable.dev&sz=128",
        "category": "development",
        "pricing_model": "freemium",
        "featured": False,
        "tags": ["code-generation"],
    },
    {
        "name": "NotebookLM",
        "slug": "notebooklm",
        "description": "NotebookLM is Google's research assistant that summarizes, grounds, and answers questions over your uploaded sources.",
        "short_description": "Google's AI research and note-taking assistant",
        "website_url": "https://notebooklm.google.com",
        "logo_url": "https://www.google.com/s2/favicons?domain=notebooklm.google.com&sz=128",
        "category": "research",
        "pricing_model": "free",
        "featured": False,
        "tags": ["text-analysis"],
    },
    {
        "name": "Suno",
        "slug": "suno",
        "description": "Suno is an AI music creation platform that generates full songs with vocals and instruments from text prompts.",
        "short_description": "AI music and song generation",
        "website_url": "https://suno.com",
        "logo_url": "https://www.google.com/s2/favicons?domain=suno.com&sz=128",
        "category": "content-creation",
        "pricing_model": "freemium",
        "featured": False,
        "tags": ["image-generation"],
    },
    {
        "name": "Ideogram",
        "slug": "ideogram",
        "description": "Ideogram is an AI image generator renowned for rendering legible text inside generated images.",
        "short_description": "AI image generation with crisp text rendering",
        "website_url": "https://ideogram.ai",
        "logo_url": "https://www.google.com/s2/favicons?domain=ideogram.ai&sz=128",
        "category": "content-creation",
        "pricing_model": "freemium",
        "featured": False,
        "tags": ["image-generation"],
    },
    {
        "name": "Leonardo.Ai",
        "slug": "leonardo-ai",
        "description": "Leonardo.Ai is a creative AI suite for generating and editing images, video, and assets for production pipelines.",
        "short_description": "Creative AI image and video generation suite",
        "website_url": "https://leonardo.ai",
        "logo_url": "https://www.google.com/s2/favicons?domain=leonardo.ai&sz=128",
        "category": "content-creation",
        "pricing_model": "freemium",
        "featured": False,
        "tags": ["image-generation"],
    },
    {
        "name": "Cohere",
        "slug": "cohere",
        "description": "Cohere provides enterprise LLM APIs for generation, retrieval, and classification with private deployments.",
        "short_description": "Enterprise LLM API platform",
        "website_url": "https://cohere.com",
        "logo_url": "https://www.google.com/s2/favicons?domain=cohere.com&sz=128",
        "category": "development",
        "pricing_model": "freemium",
        "featured": False,
        "tags": ["api-integration"],
    },
    {
        "name": "Meta Llama",
        "slug": "meta-llama",
        "description": "Llama is Meta's family of open-weights large language models for chat, coding, and tool use.",
        "short_description": "Meta's open-weights LLM family",
        "website_url": "https://llama.com",
        "logo_url": "https://www.google.com/s2/favicons?domain=llama.com&sz=128",
        "category": "development",
        "pricing_model": "free",
        "featured": False,
        "tags": ["api-integration"],
    },
    {
        "name": "Kimi",
        "slug": "kimi",
        "description": "Kimi is an AI assistant from Moonshot AI known for long-context understanding and document analysis.",
        "short_description": "Long-context AI assistant by Moonshot AI",
        "website_url": "https://kimi.com",
        "logo_url": "https://www.google.com/s2/favicons?domain=kimi.com&sz=128",
        "category": "productivity",
        "pricing_model": "freemium",
        "featured": False,
        "tags": ["conversational-ai"],
    },
]